version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    # command: /usr/local/bin/docker-entrypoint.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'